### ISSUE TITLE
Highlighting wrong with plugin mg979/vim-visual-multi for "current" multi cursor

### ISSUE THREAD

**Issue by alexander-born** [sainnhe/everforest#67] opened 2022-05-30 07:55 UTC
### Operating system/version

Ubuntu 20.04

### Terminal emulator/version

bash

### $TERM environment variable

tmux-256color

### Tmux version

tmux 3.0a

### Feature matrix
<details>

```text

null-ls: require("null-ls.health").check()
========================================================================
  - OK: black: the command "black" is executable.
  - OK: buildifier: the command "buildifier" is executable.
  - OK: clang_format: the command "clang-format" is executable.
  - OK: json_tool: the command "python" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='6003'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Go**: not available
  - WARNING: **cargo**: not available
  - WARNING: **luarocks**: not available
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.1.0`
  - OK: **node**: `v16.13.0`
  - OK: **python3**: `Python 3.8.10`
  - WARNING: **pip3**: not available
  - WARNING: **javac**: not available
  - OK: **java**: `Ok`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.20.3 built on linux-gnu.`
  - OK: **curl**: `curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3`
  - OK: **gzip**: `gzip 1.10`
  - OK: **tar**: `tar (GNU tar) 1.30`
  - OK: **bash**: `GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: GitHub API rate limit. Used: 0. Remaining: 5000. Limit: 5000. Reset: Mo 30 Mai 2022 10:11:13 CEST.

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.13.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.8.10
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.13.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 11.0.2
  - OK: fd: found fd 7.4.0

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/q456457/.local/state/nvim/lsp.log
  - INFO: Log size: 46801 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for c: ABI version 13


```
</details>

### Minimal vimrc that can reproduce this bug.

```vim
call plug#begin()
Plug 'sainnhe/everforest'
Plug 'mg979/vim-visual-multi'
call plug#end()

set termguicolors
colorscheme everforest
```

### Steps to reproduce this bug using minimal vimrc
```text
1. Launch vim/nvim
2. start multi cursor with <C-n> press n for next occurence
3. move cursor around

1. Launch vim/nvim
2. start multi cursor with <C-arrowDown>
```

### Expected behavior

current multi cursor highlighted

### Actual behavior

current multi cursor flickers in visual mode / not highlighted in normal mode see gifs
![multicursorbug2](https://user-images.githubusercontent.com/61082865/170945169-8eb2fea7-3949-4175-9559-c5f76aa46b65.gif)
![multicursorbug](https://user-images.githubusercontent.com/61082865/170944787-820fe35d-1d01-46a7-94fd-7db76b7cc594.gif)

**Comment by alexander-born** [comment] 2022-05-30 08:44
Probably these need to be modified
https://github.com/sainnhe/everforest/blob/ee24cd4bde3fea5c536a6a319900683825b16adc/colors/everforest.vim#L728-L731

**Comment by sainnhe** [comment] 2022-05-30 12:05
![截屏2022-05-30 下午8 03 55](https://user-images.githubusercontent.com/37491630/170988634-df9520f9-2424-4436-9b25-c14565eb7c1a.png)

I can't reproduce this, and I don't think it's a bug in color scheme level.

Can you retry with default color scheme?

**Comment by alexander-born** [comment] 2022-05-31 07:39
With the default color scheme there is no issue.

I tested again with the minimal config and can reproduce the issue. Just the blinking is not there with with minimal config.
Still the current multi cursor is not highlighted correctly.

Btw I love this colorscheme <3

**Comment by sainnhe** [comment] 2022-05-31 07:48
Sorry, I have no idea what's going on. Help wanted.

**Comment by alexander-born** [comment] 2022-05-31 08:47
I just played around with the highlight groups.
When using these it works as expected:
```viml
call everforest#highlight('MultiMonoHl', g:everforest_palette.fg, g:everforest_palette.red)
call everforest#highlight('MultiCursorHl', g:everforest_palette.fg, g:everforest_palette.orange)
let g:VM_Mono_hl = 'MultiMonoHl'
let g:VM_Extend_hl = 'Visual'
let g:VM_Cursor_hl = 'MultiCursorHl'
let g:VM_Insert_hl = 'DiffChange'
```
![multicursorbugfix](https://user-images.githubusercontent.com/61082865/171132639-43761e11-545c-46db-994d-4614e0951f18.gif)

**Comment by sainnhe** [comment] 2022-05-31 08:59
Does this work for you?

```vim
call everforest#highlight('VMCursor', s:palette.bg0, s:palette.fg)
let g:VM_Mono_hl = 'VMCursor'
let g:VM_Extend_hl = 'Visual'
let g:VM_Cursor_hl = 'VMCursor'
let g:VM_Insert_hl = 'VMCursor'
```

**Comment by alexander-born** [comment] 2022-05-31 09:09
It has issues I find. In blank spaces you dont see the cursor. see:
![multicursorbugfix2](https://user-images.githubusercontent.com/61082865/171137370-d54ce7c8-687c-4b6f-b038-53bc3dc242e8.gif)


Btw I also have this in my config to improve diffs to my liking, what do you think?
```viml
autocmd ColorScheme everforest call everforest#highlight('DiffText', ['NONE', 'NONE', 'NONE'], ['#546b76', '17', 'LightBlue'])
```
![image](https://user-images.githubusercontent.com/61082865/171135939-7ee054dd-25a6-4d09-bb31-43ce99b6395b.png)
vs default
![image](https://user-images.githubusercontent.com/61082865/171136193-4a03ca2e-3933-4f63-8c95-062b3f44258c.png)

**Comment by sainnhe** [comment] 2022-05-31 09:27
This is really strange.

In your code:

```vim
call everforest#highlight('MultiMonoHl', g:everforest_palette.fg, g:everforest_palette.red)
call everforest#highlight('MultiCursorHl', g:everforest_palette.fg, g:everforest_palette.orange)
let g:VM_Mono_hl = 'MultiMonoHl'
let g:VM_Extend_hl = 'Visual'
let g:VM_Cursor_hl = 'MultiCursorHl'
let g:VM_Insert_hl = 'DiffChange'
```

The hi group of `MultiMonoHl` uses fg and foreground color and use red as background color. Did you notice that the characters under the cursors are barely visible? The foreground color and background color are hard to distinguish from, that's why I changed the fg to bg0. The foreground color becomes black so the characters are more visible. (Btw, you should use `s:palette.fg` instead of `g: everforest_palette.fg`.)

But when I changed the foreground color to bg0, the background color of current cursor also goes to black... So strange, the color of current cursor is controlled by terminal emulators in most of the time and should not be changed.

---

I want to try to reproduce this. What's the terminal emulator you are using?

In the info you provided, the terminal emulator section is filled with `bash`. `bash` is a shell, not a terminal emulator. A terminal emulator is something like gnome terminal, konsole and iterm2, it's the app you launched to enter a terminal. So what's the terminal emulator you are using?

**Comment by sainnhe** [comment] 2022-05-31 11:50
Should be fixed now.

**Closed by sainnhe** 2022-05-31 11:50 UTC
Labels: bug, help wanted

**Comment by alexander-born** [comment] 2022-05-31 12:22
Thanks love the new look :)
